apiVersion: v1
kind: Service
metadata:
  name: cvss-backend
spec:
  type: NodePort
  selector:
    app: cvss-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
