apiVersion: v1
kind: PersistentVolume
metadata:
  name: feedback-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/feedback
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feedback-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
