apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvss-mlservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvss-mlservice
  template:
    metadata:
      labels:
        app: cvss-mlservice
    spec:
      containers:
        - name: cvss-mlservice
          image: sengar001/cvss-mlservice:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: feedback-storage
              mountPath: /app/dataset
      volumes:
        - name: feedback-storage
          persistentVolumeClaim:
            claimName: feedback-pvc
