apiVersion: v1
kind: Service
metadata:
  name: cvss-mlservice
spec:
  type: NodePort
  selector:
    app: cvss-mlservice
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
