apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvss-mlservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvss-mlservice
  template:
    metadata:
      labels:
        app: cvss-mlservice
    spec:
      containers:
        - name: cvss-mlservice
          image: sengar001/cvss-mlservice:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          volumeMounts:
            - name: feedback-storage
              mountPath: /app/dataset
            - name: model-storage
              mountPath: /app/model
      volumes:
        - name: feedback-storage
          persistentVolumeClaim:
            claimName: feedback-pvc
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-pvc
