---
# - name: Install Docker
#   apt:
#     name: docker.io
#     state: present
#     update_cache: true

# - name: Install Docker Compose
#   apt:
#     name: docker-compose
#     state: present

- name: Start all Docker Compose services
  command: docker-compose up -d
  args:
    chdir: "{{ playbook_dir }}/.."
