- name: Deploy CVSS Stack
  hosts: all
  become: true
  vars_files:
    - secrets.yml
  vars:
    ansible_become_pass: "{{ ansible_become_password }}"
  roles:
    - { role: docker, tags: ["docker"] }
